global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'
route:
  receiver: 'slack-notifications'
 
receivers:
- name: 'slack-notifications'
 slack_configs:
 - channel: '#alertmanager'
   send_resolved: true
